### ISSUE TITLE
RSVP API

### ISSUE THREAD

**Issue by LERoise** [Itera/mad-learning-web#12]
### Features
* RSVP for a event

**Comment by duytantran** [comment]
Working on the branch `rsvp-event`.

**Comment by duytantran** [comment]
Backend tested in Postman and it works. Started a rsvp-event branch for the frontend part and have currently only implemented the PUT method for RSVP. Need to add a button or something for the RSVP to connect in both `EventPage.tsx` and `Landingpage.tsx`.
