### ISSUE TITLE
Fix CORS

### ISSUE THREAD

**Issue by martinAtItera** [Itera/mad-learning-web#18]

**Comment by martinothamar** [comment]
Did you have any specific error? This issue will depend on how the infra is implemented, i.e. if frontend and API will be behind same domain name or not

**Comment by martinAtItera** [comment]
Had a problem with CORS during develop, could not access API locally due to CORS. Made a local temp fix in the API and talked to Lars Erik who said I should create a task.

**Comment by martinAtItera** [comment]
Error: Access to fetch at 'https://localhost:5001/api/Event' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by anhtin** [comment]
@martinothamar We should probably configure the backend to whitelist all localhost origins when running locally. I think @LERoise had some input on how this could be achieved.

**Comment by martinothamar** [comment]
Yes I can add CORS policy

**Comment by martinothamar** [comment]
https://github.com/Itera/mad-learning-web/pull/25
https://github.com/Itera/mad-learning-api/pull/11
