### ISSUE TITLE
Missing fields in event model

### ISSUE THREAD

**Issue by martinAtItera** [Itera/mad-learning-web#19]
Can the eventmodel be updated with the following fields:
image
imageAlt
location
eventType (this is a suggestion from me, but might be nice to filter on types)

**Comment by martinothamar** [comment]
Woops never saw this issue, sorry. Feel free to @mention me in the future.

* `location`, should that just be a free-form text field? I.e. any constraints on the input?
* Should `eventType` be based on an enum or something similar?

**Comment by martinAtItera** [comment]
Yes sounds ok. But maybe we should have a talk with @LERoise and get his thoughts? Eventtype was just a suggestion, but might come in handy.

**Comment by anhtin** [comment]
Closed by Itera/mad-learning-api#10.
