### ISSUE TITLE
LandingPage bugs

### ISSUE THREAD

**Issue by LERoise** [Itera/mad-learning-web#42]
- [x] Redirect to landing page on event created
- [x] Popup with persmissions are blocked, not easy for the user to notice and understand 
- [x] If event fails to load image, it should still take up the same space as others.
- [x] Set max width of landing-area section (it gets real big with 4k resolution)
- [x] Navigation bar does look like a navbar
- [x] Show which page you are at in navbar
- [x] Past events should not be show
- [x] Possible to change RSVP

**Comment by martinothamar** [comment]
Some past events are shown, 12 hours back in time, for in progress events and if people update the description etc
