### ISSUE TITLE
Teams link: Restrict the field to only allow team-links.

### ISSUE THREAD

**Issue by LERoise** [Itera/mad-learning-web#80]
System response on sentence with %: "URIError: Failed to decode param '/event/613f45a9fb4c2ebd902cdfed/HeiURL!!!;);););)%%%%'...." 

System response with string without %: Page try to find the element on the page, but can't find it (link: http://localhost:3000/event/613f51cafb4c2ebd902cdfee/HeiURL$$%E2%82%AC). 

System response with link, e.g. https://www.vg.no: redirects to vg.no.

UPDATE 21.sept: No longer possible to write other formats than link, but still possible to add other types of link than Team's link. Partly solved.

**Comment by erlenste** [comment]
Yup has option for Regex, so that might be an option in addition to a Yup-URL check
